#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

#define LV_COLOR_DEPTH 32
#define LV_MEM_SIZE (48U * 1024U * 1024U)

#ifndef SDL_HOR_RES
#define SDL_HOR_RES 1280
#endif
#ifndef SDL_VER_RES
#define SDL_VER_RES 800
#endif

#define LV_USE_SDL 1
#define LV_SDL_WINDOW_TITLE "screen-desktop"
#define LV_SDL_INCLUDE_PATH <SDL2/SDL.h>

#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_MONTSERRAT_30 1
#define LV_FONT_MONTSERRAT_32 1
#define LV_FONT_MONTSERRAT_40 1
#define LV_FONT_MONTSERRAT_48 1
#define LV_USE_FONT_COMPRESSED 1

#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_LOG_PRINTF 1

#define LV_USE_TJPGD 1
#define LV_USE_LODEPNG 1
#define LV_USE_RLE 1
#define LV_USE_LZ4_INTERNAL 1
#define LV_BIN_DECODER_RAM_LOAD 1
#define LV_USE_FLOAT 1
#define LV_USE_MATRIX 1
#define LV_USE_VECTOR_GRAPHIC 0
#define LV_USE_THORVG_INTERNAL 0
#define LV_USE_SVG 0
#define LV_USE_SVG_ANIMATION 0
#define LV_USE_SVG_DEBUG 0
#define LV_CACHE_DEF_SIZE (24U * 1024U * 1024U)

#define LV_USE_STDLIB_MALLOC LV_STDLIB_BUILTIN
#define LV_USE_STDLIB_STRING LV_STDLIB_BUILTIN
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_BUILTIN

#define LV_USE_CANVAS 1
#define LV_USE_QRCODE 1

#endif
